In [3]:
from collections import defaultdict

In [27]:
import numpy as np
import tensorflow as tf

In [ ]:
(sic, key=dict.get)

In [4]:
sic = defaultdict(lambda:0)

In [7]:
[ch for ch in dir(sic) if "_" not in ch]

['clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [59]:
y_true = [[0, 1], [0, 0]]
y_pred = [[0.6, 0.4], [0.4, 0.6]]
loss = tf.keras.losses.binary_crossentropy(y_true, y_pred,from_logits=True)
assert loss.shape == (2,)

In [56]:
import tensorflow as tf
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# NumPy
numpy_result = arr / np.sqrt(np.sum(np.square(arr), axis=1)).reshape(-1, 1)

numpy_result2 = arr / np.linalg.norm(arr, ord=2, axis=1 ).reshape(-1,1)
# TensorFlow
tf_result, _ = tf.linalg.normalize(tf.dtypes.cast(tf.constant(arr), tf.float32), ord='euclidean', axis=1)

print("NumPy Result:")
print(numpy_result)

print("\nNumPy Result2:")
print(numpy_result2)

print("\nTensorFlow Result:")
print(tf_result)


tf_norm = tf.linalg.norm(tf.dtypes.cast(tf.constant(arr), tf.float32), ord='euclidean', axis=1)
np_norm = np.linalg.norm(arr, ord=2, axis=1 )


print("\nTensorFlow Norm:")
print(tf_norm)

print("\nNumpy Norm:")
print(np_norm)

NumPy Result:
[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]]

NumPy Result2:
[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]]

TensorFlow Result:
tf.Tensor(
[[0.26726124 0.5345225  0.8017837 ]
 [0.45584232 0.5698029  0.68376344]], shape=(2, 3), dtype=float32)

TensorFlow Norm:
tf.Tensor([3.7416575 8.774964 ], shape=(2,), dtype=float32)

Numpy Norm:
[3.74165739 8.77496439]


In [31]:
arr = np.arange(24).reshape(6,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
arr / np.sqrt(np.sum(np.square(arr), axis=1)).reshape(-1,1)

array([[0.        , 0.26726124, 0.53452248, 0.80178373],
       [0.35634832, 0.4454354 , 0.53452248, 0.62360956],
       [0.4181667 , 0.47043754, 0.52270837, 0.57497921],
       [0.44292808, 0.47983876, 0.51674943, 0.5536601 ],
       [0.45621276, 0.48472606, 0.51323935, 0.54175265],
       [0.46448868, 0.48771311, 0.51093754, 0.53416198]])

In [41]:
narr = tf.linalg.normalize(tf.dtypes.cast(tf.constant(arr), tf.float32), ord='euclidean')
narr

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[0.        , 0.01520748, 0.03041495, 0.04562243],
        [0.06082991, 0.07603738, 0.09124486, 0.10645234],
        [0.12165982, 0.1368673 , 0.15207477, 0.16728225],
        [0.18248972, 0.1976972 , 0.21290468, 0.22811216],
        [0.24331963, 0.2585271 , 0.2737346 , 0.28894207],
        [0.30414954, 0.31935704, 0.3345645 , 0.34977198]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[65.757126]], dtype=float32)>)

In [35]:
np.linalg.norm(arr, ord=2, axis=1 )

array([ 3.74165739, 11.22497216, 19.13112647, 27.09243437, 35.07135583,
       43.05810028])

In [22]:
np.linalg.norm(arr, ord=2, axis=1 )

array([ 3.74165739, 11.22497216, 19.13112647, 27.09243437, 35.07135583,
       43.05810028])

In [ ]:
np.linalg.(arr)