In [25]:
isinstance("s",([] or str))

True

In [3]:
import numpy as np

In [20]:
np.random.seed(30)
fir = np.random.randint(5,size=(3,3))
sec = np.random.randint(3,size=(3,3))
print(fir, "\n")
print(sec)

[[4 4 2]
 [3 1 3]
 [1 1 1]] 

[[1 1 2]
 [2 0 0]
 [2 0 0]]


In [33]:
fir[:,:,None]

array([[[4],
        [4],
        [2]],

       [[3],
        [1],
        [3]],

       [[1],
        [1],
        [1]]])

In [34]:
fir[...,:,None]

array([[[4],
        [4],
        [2]],

       [[3],
        [1],
        [3]],

       [[1],
        [1],
        [1]]])

In [38]:
fir[...,None,:]

array([[[4, 4, 2]],

       [[3, 1, 3]],

       [[1, 1, 1]]])

In [40]:
fir[None,:]

array([[[4, 4, 2],
        [3, 1, 3],
        [1, 1, 1]]])

In [21]:
np.equal(fir,sec).astype(np.float32)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [49]:
if not 0:
    print("hi")

hi


In [25]:
share = fir is not None
share

True

In [52]:
[ch for ch in dir(list) if "_" not in ch]

['append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [51]:
[3,2,4,5].replace(2,3)

AttributeError: 'list' object has no attribute 'replace'

In [ ]:
isinstance("s",(str or bytes))b
isinstance("s",(str | bytes))
isinstance("s",(str and bytes))
isinstance("s",(bytes or str))
isinstance("s",(bytes | str))
isinstance("s",(bytes and str))

In [53]:
[ch for ch in dir(dict) if "_" not in ch]

['clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [54]:
"this is the best".replace("this", "ok" )

'ok is the best'

In [49]:
thir = np.random.rand(5,5,4,2)

In [51]:
thir.shape

(5, 5, 4, 2)

In [55]:
np.transpose(thir, [1,0,3,2]).shape

(5, 5, 2, 4)

In [58]:
if not len(thir)==0:
    print("hi")

hi


In [65]:
np.ceil(5//2)

2.0

In [70]:
thir.shape

(5, 5, 4, 2)

In [69]:
thir.reshape(-1,thir.shape[-2]).shape

(50, 4)

In [76]:
np.random.normal(77, 20)

83.02167796474964

In [78]:
!pip install fastmath

In [79]:
import fastmath

array([[ 3.00118322, -0.43767669,  1.93696351,  1.0364238 ,  4.26693907],
       [ 4.22302048,  0.53144539,  6.46774634,  3.20007425,  2.58524954],
       [ 4.00055718,  3.03108762,  3.77667749,  0.08793861,  8.31091317],
       [ 1.7159588 ,  8.14709795,  3.47806517,  5.19538991,  3.51880864]])

In [87]:
import os 

In [91]:
os.getcwdb()

b'E:\\DeepLearning.AI-Natural-Language-Processing-Specialization-main\\4-Natural Language Processing with Attention Models\\Week 3\\Assignment'

In [92]:
os.getcwd()

'E:\\DeepLearning.AI-Natural-Language-Processing-Specialization-main\\4-Natural Language Processing with Attention Models\\Week 3\\Assignment'

In [94]:
from termcolor import colored

In [97]:
print(colored("this is best", "green"))

this is best


In [110]:
np.random.seed(2)
set = np.random.randint(5,size=(3,4,4))
set

array([[[0, 0, 3, 2],
        [3, 0, 2, 1],
        [3, 2, 4, 4],
        [4, 3, 4, 2]],

       [[3, 3, 2, 1],
        [2, 4, 3, 0],
        [4, 3, 1, 2],
        [0, 4, 4, 2]],

       [[4, 2, 1, 0],
        [2, 2, 1, 0],
        [1, 0, 2, 1],
        [1, 1, 4, 2]]])

In [111]:
x1, x2 = np.split(set, 2, axis=-1) 

In [112]:
x1

array([[[0, 0],
        [3, 0],
        [3, 2],
        [4, 3]],

       [[3, 3],
        [2, 4],
        [4, 3],
        [0, 4]],

       [[4, 2],
        [2, 2],
        [1, 0],
        [1, 1]]])