In [2]:
import numpy as np
from scipy.linalg import triu, tril

def split_matrix(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Input matrix must be square.")

    upper_triangular = triu(matrix)
    lower_triangular = tril(matrix)
    diagonal = np.diag(np.diag(matrix))

    return upper_triangular, lower_triangular, diagonal

# Example usage:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

upper, lower, diag = split_matrix(matrix)

print("Original Matrix:")
print(matrix)

print("\nUpper Triangular Matrix:")
print(upper)

print("\nLower Triangular Matrix:")
print(lower)

print("\nDiagonal Matrix:")
print(diag)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Upper Triangular Matrix:
[[1 2 3]
 [0 5 6]
 [0 0 9]]

Lower Triangular Matrix:
[[1 0 0]
 [4 5 0]
 [7 8 9]]

Diagonal Matrix:
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [4]:
np.diag(np.diag(matrix))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [7]:
mask_size = 2
np.tril(np.ones((1, mask_size, mask_size), dtype=np.bool_), k=0) 

array([[[ True, False],
        [ True,  True]]])

In [11]:
import numpy as np

In [12]:
def create_tensor(t):
    """Create tensor from list of lists"""
    return np.array(t)


def display_tensor(t, name):
    """Display shape and tensor"""
    print(f'{name} shape: {t.shape}\n')
    print(f'{t}\n')

In [13]:
q = create_tensor([[1, 0, 0], [0, 1, 0]])
display_tensor(q, 'query')
k = create_tensor([[1, 2, 3], [4, 5, 6]])
display_tensor(k, 'key')
v = create_tensor([[0, 1, 0], [1, 0, 1]])
display_tensor(v, 'value')
m = create_tensor([[0, 0], [-1e9, 0]])
display_tensor(m, 'mask')

query shape: (2, 3)

[[1 0 0]
 [0 1 0]]

key shape: (2, 3)

[[1 2 3]
 [4 5 6]]

value shape: (2, 3)

[[0 1 0]
 [1 0 1]]

mask shape: (2, 2)

[[ 0.e+00  0.e+00]
 [-1.e+09  0.e+00]]



In [26]:
dots = q @ k.T / np.sqrt(3)
display_tensor(q_dot_k, 'query dot key')

query dot key shape: (2, 2)

[[0.57735027 2.30940108]
 [1.15470054 2.88675135]]



In [37]:
mask = np.tril(np.ones((1,4,4),dtype=np.bool_),k=0)
mask

array([[[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False],
        [ True,  True,  True,  True]]])

In [49]:
np.random.seed(3)
dots = np.random.normal(4,2, (1,4,4))
dots

array([[[7.57725695, 4.8730197 , 4.19299494, 0.27301459],
        [3.44522359, 3.29048204, 3.83451704, 2.74599865],
        [3.91236366, 3.04556394, 1.37227049, 5.76924476],
        [5.76263608, 7.41914613, 4.10006728, 3.19064517]]])

In [50]:
np.where(mask, dots, np.full_like(dots, -1e9))

array([[[ 7.57725695e+00, -1.00000000e+09, -1.00000000e+09,
         -1.00000000e+09],
        [ 3.44522359e+00,  3.29048204e+00, -1.00000000e+09,
         -1.00000000e+09],
        [ 3.91236366e+00,  3.04556394e+00,  1.37227049e+00,
         -1.00000000e+09],
        [ 5.76263608e+00,  7.41914613e+00,  4.10006728e+00,
          3.19064517e+00]]])

In [ ]:
np.where()

In [51]:
import os

In [52]:
os.getcwd()

'E:\\DeepLearning.AI-Natural-Language-Processing-Specialization-main\\4-Natural Language Processing with Attention Models\\Week 1\\Assignment'

In [62]:
os.path.expanduser("~\data")

'C:\\Users\\Hp\\data'

In [68]:

import textwrap
wrapper = textwrap.TextWrapper(width=20)



In [69]:
sentence = "this is most beautiful day i have ever seen in the karachi"
print(wrapper.fill(sentence),"\n")

this is most
beautiful day i have
ever seen in the
karachi 



In [5]:
mask = np.random.rand(2,3)

In [9]:
mask.shape

(2, 3)

In [10]:
np.reshape(mask, (mask.shape[0], 1, 1, mask.shape[1])).shape

(2, 1, 1, 3)